swagger: "2.0"
info:
  title: "TOPCODER EMAIL SERIES - EMAIL SERVER"
  description: "TOPCODER EMAIL SERIES - EMAIL SERVER"
  version: "1.0.0"
host: "localhost:4001"
schemes:
- "http"
securityDefinitions:
  jwt:
    type: apiKey
    name: Authorization
    in: header
    description: JWT Authentication. Provide API Key in the form 'Bearer &lt;token&gt;'.

paths:
  /templates/eventType/{name}:
    get:
      description:
        get email template placholders name
      produces:
        - application/json
      security:
        - jwt: []
      parameters:
        - name: name
          in: path
          description: The Kafka topic name
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  type: string
        400:
          description: "Bad request error."
          schema:
            $ref: "#/definitions/Error"
       404:
         description: "Template is not found error."
         schema:
            $ref: "#/definitions/Error"
        401:
          description: "Authentication failed."
          schema:
            $ref: "#/definitions/Error"
        500:
          description: "Internal server error."
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    properties:
      error:
        type: string
      details:
        type: array
        items:
          type: object
          properties:
            message:
              type: string
            path:
              type: string
            type:
              type: string
            context:
              type: object
